language: java

before_install:
  - docker pull maven
  - export GPG_TTY=$(tty)
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install: mvn clean install -DskipTests=true -Dgpg.skip

jobs:
  include:
  - stage: deploy
    if: branch =~ ^[0-9]+.[0-9]+$
    script: mvn release:clean; mvn -X --batch-mode -Dtag=$TRAVIS_BRANCH -DreleaseVersion=$TRAVIS_BRANCH -DdevelopmentVersion=2.2-SNAPSHOT -DdryRun=true release:prepare
