language: java

before_install:
  - docker pull maven
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install: mvn --settings .maven.xml clean install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
  - stage: deploy
    if: branch =~ ^[0-9]+.[0-9]+$
    script: mvn release:clean; mvn --batch-mode -Dtag=$TRAVIS_BRANCH -DreleaseVersion=$TRAVIS_BRANCH
      -DdevelopmentVersion=2.2-SNAPSHOT -DdryRun=true release:prepare
