language: java
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install: mvn clean install -DskipTests=true -Dgpg.skip

deploy:
  provider: script
  script: mvn clean deploy --settings settings.xml -Dgpg.executable=$GPG_EXECUTABLE -Dgpg.keyname=$GPG_KEYNAME -Dgpg.passphrase=$GPG_PASSPHRASE
  on:
    all_branches: true
    condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^[0-9]+.[0-9]+$

